name = "Eogend Modpack"
author = "Monodia3007, AlexisHuvier"
version = "0.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9dcd93784d55f98251e2f2eaf5c20ff20f535ff4af53a9b033aa6efd3d7cddb6"

[versions]
fabric = "0.15.4"
minecraft = "1.20.1"
