name = "Eogend Modpack"
author = "Monodia3007, AlexisHuvier"
version = "0.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b265293d3ff682d0baf729e24d2c057a44f92f80b5e4894750aecc95c64d6722"

[versions]
fabric = "0.15.4"
minecraft = "1.20.1"
